name: 'Background Server'
description: 'Spin up a server in the background for tests and other stuff'
author: 'Bernhard Wittmann'
inputs:
  command:
    description: 'Main command to run'
    required: true
  command-windows:
    description: 'Main command to run on Windows'
    required: true
  build:
    description: 'Command to run in build step before starting main command'
    required: false
  start:
    description: 'Command for starting local server in the background'
    required: false
  start-windows:
    description: 'A different start command on Windows'
    required: false
  wait-on:
    description: 'Local server URL to wait for'
    required: false
  wait-on-timeout:
    description: 'Amount of time to wait for wait-on url to be available'
    required: false
  cwd:
    description: 'Current working directory'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: 'purple'
  icon: 'server'