name: "units-test"
on:
  pull_request:
  push:

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          node-version: 16
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          node-version: 16
    - uses: ./
      with:
        command: cat ./test.txt
        build: echo "test-file-content" > ./test.txt && ls
